### ISSUE TITLE
'Attachment model missing type definition for' errors

### ISSUE THREAD

**Issue by jgedarovich** [cleentfaar/slack#66]
While testing out this library I ran into the same problems as described in #59 . However, after applying the patch from #59 locally I found that It required further modifications, the full list of additions to [CL.Slack.Model.Attachment.yml](https://github.com/cleentfaar/slack/blob/master/src/CL/Slack/Resources/config/serializer/CL.Slack.Model.Attachment.yml) that worked for me was:

```

        mrkdwnIn:
            type: array
        titleLink:
            type: string
        authorName:
            type: string
        authorLink:
            type: string
        authorIcon:
            type: string

```

PR to follow.
